### PR TITLE
Handle invalid layer other than vector in the legend

### PR DESCRIPTION
**Pull request by Gustry**
Linked to https://github.com/3liz/lizmap-web-client/issues/4397

In the `GetLegendGraphic`, check all kind of layer if it is invalid or not

CC @guenterw

### CODE REVIEW

**Review by rldhont — APPROVED** [review]
Good catch!

**Comment by Gustry** [comment]
Note for myself, I should check the JSON for a valid raster layer, just in case ...

**Comment by Gustry** [comment]
@rldhont and @guenterw, to make tests passing, we can clearly notice how the legend was broken between 3.22 included and 3.34 excluded for raster.

So we should encourage people to migrate soon to 3.34.

**Comment by guenterw** [comment]
ok, I will pass this on to the German users (mailing list).

Regarding new functions, I'm sure everyone will understand. It is somewhat more annoying for the user if something no longer works in new versions as it used to in the older version (e.g. the legend in V3.7 with QGIS 3.22).
Technically, of course, I understand that. The alternative would have been that 3.7 could only be used with QGIS 3.28 or 3.34. It's always a compromise.

I personally plan to use 3.8 with QGIS 3.34 for major upgrades or new projects. Ideally under Ubuntu 24.04, provided this is available from my web host (Hetzner) in good time. Then hopefully there will be peace and quiet for a while :)

Thanks for the intensive work on Lizmap.

**Pull request merged**
