### PR TITLE
Spatial filter - Use a QGIS expression instead of plain SQL

### LINKED ISSUE #15: Spatial filtering : use centroid and spatial index check
* [x] When saving the CFG file, check for PG layer and if the index exists
* [x] the check can be done at different level, TBD
* [x] add a button to create it if possible

CC @mdouchin

### PR DESCRIPTION
**Pull request by Gustry**
Spatial filter - Use a QGIS expression instead of plain SQL

- [ ] Switch to WKB instead of WKT in the QGIS expression ?

Fix #15

### CODE REVIEW

**Comment by rldhont** [comment]
Is it possible to add a test with getfeatureinfo ?

**Comment by Gustry** [comment]
I just added #15 in this PR as well because the code is quite related and a lof of conflicts in this area. But it still in the separate commit, easier for review.

Linked to https://github.com/3liz/lizmap-plugin/pull/446

**Comment by rldhont** [comment]
Once #19 is merged this one could be too.

**Review by rldhont — APPROVED** [review]
Tested with #19 included and all tests passed!

**Pull request merged**
